ci: reduce ci time

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -36,12 +36,29 @@ jobs:
       matrix:
         include:
           - name: Runtime
-          - name: Runtime IT
+            test_cmd: ./mvnw -ntp package -pl ":langstream-runtime-impl"
+            build_docker: false
+          - name: Runtime IT (Group 0)
+            build_docker: true
+            test_cmd: ./mvnw -ntp failsafe:integration-test failsafe:verify -pl ":langstream-runtime-impl" -PskipPython
+          - name: Runtime IT (Group 1)
+            build_docker: true
+            test_cmd: ./mvnw -ntp failsafe:integration-test failsafe:verify -pl ":langstream-runtime-impl" -PskipPython
           - name: Deployer
+            build_docker: false
+            test_cmd: ./mvnw -ntp verify -f langstream-k8s-deployer -Pdocker -PskipPython
           - name: Api Gateway
+            build_docker: false
+            test_cmd: ./mvnw -ntp verify -pl ":langstream-api-gateway" -Pdocker -PskipPython
           - name: Control plane
+            build_docker: false
+            test_cmd: ./mvnw -ntp verify -pl langstream-webservice -Pdocker -PskipPython
           - name: Other
+            build_docker: false
+            test_cmd: ./mvnw -ntp verify -PtestSuiteOthers -PskipPython
           - name: Style
+            build_docker: false
+            test_cmd: mvn clean install -DskipTests -PskipPython,generateDoc
     steps:
       - name: 'Setup: checkout project'
         uses: actions/checkout@v2
@@ -73,75 +90,37 @@ jobs:
           chmod +x mvnw
           ./mvnw -ntp clean install -DskipTests -PskipPython
 
-      - name: 'Test: Runtime'
-        if: ${{ matrix.name == 'Runtime' }}
+      - name: 'Test: ${{ matrix.name }}'
         run: |
-          ./mvnw -ntp package -pl ":langstream-runtime-impl"
+          if ${{ matrix.build_docker }}; then
+            echo "::group::Build runtime docker images"
+            ./mvnw -ntp package -pl ":langstream-runtime-base-docker-image" -Pdocker -DskipTests -PskipPython
+            echo "::endgroup::"
+            echo "::group::Build module"
+            ./mvnw -ntp package -pl ":langstream-runtime-impl" -Pdocker -DskipTests -PskipPython
+            echo "::endgroup::"
+            
+            # cleanup intermediate layers to save space
+            docker system prune -f
+            docker image prune -f
+            sudo du -sh *
+            docker images
+            echo "Cleaning up docker images"
+            (docker images | grep -v -e 'langstream' -e 'none' | tail -n +2 | awk -F ' ' '{print $1,":",$2}' | tr -d ' ' | xargs -I {} docker rmi -f {}) || echo "Failed to remove images"
+            echo "After cleanup"
+            docker images
+            sudo du -sh *
+          fi
+          echo "::group::Run tests"
+          ${{ matrix.test_cmd }}
+          echo "::endgroup::"
           if [[ `git status --porcelain` ]]; then
-            echo "Found runtime impl changed after building, please build the runtime impl and commit the changes. "
+            echo "Found changes after building, please verify. (re-build the CRDs or run ./mvnw spotless:apply might help)"
             git status
             git diff
             exit 1
           fi
 
-      - name: 'Test: Runtime (Integration Tests)'
-        if: ${{ matrix.name == 'Runtime IT' }}
-        run: |
-          echo "::group::Build runtime docker images"
-          ./mvnw -ntp package -pl ":langstream-runtime-base-docker-image" -Pdocker -DskipTests -PskipPython
-          echo "::endgroup::"
-          echo "::group::Build module"
-          ./mvnw -ntp package -pl ":langstream-runtime-impl" -Pdocker -DskipTests -PskipPython
-          echo "::endgroup::"
-          
-          # cleanup intermediate layers to save space
-          docker system prune -f
-          docker image prune -f
-          sudo du -sh *
-          docker images
-          echo "Cleaning up docker images"
-          (docker images | grep -v -e 'langstream' -e 'none' | tail -n +2 | awk -F ' ' '{print $1,":",$2}' | tr -d ' ' | xargs -I {} docker rmi -f {}) || echo "Failed to remove images"
-          echo "After cleanup"
-          docker images
-          sudo du -sh *
-          
-
-
-          echo "::group::Run integration tests"
-          ./mvnw -ntp failsafe:integration-test failsafe:verify -pl ":langstream-runtime-impl" -PskipPython
-          echo "::endgroup::"
-
-      - name: 'Test: Api Gateway'
-        if: ${{ matrix.name == 'Api Gateway' }}
-        run: |
-          ./mvnw -ntp verify -pl ":langstream-api-gateway" -Pdocker -PskipPython
-
-      - name: 'Test: Deployer'
-        if: ${{ matrix.name == 'Deployer' }}
-        run: |
-          ./mvnw -ntp verify -f langstream-k8s-deployer -Pdocker -PskipPython
-
-      - name: 'Test: Control plane'
-        if: ${{ matrix.name == 'Control plane' }}
-        run: |
-          ./mvnw -ntp verify -pl langstream-webservice -Pdocker -PskipPython
-
-      - name: 'Test: Other'
-        if: ${{ matrix.name == 'Other' }}
-        run: |
-          #/bin/bash
-          ./mvnw -ntp verify -PtestSuiteOthers -PskipPython
-      - name: 'Test: Style'
-        if: ${{ matrix.name == 'Style' }}
-        run: |
-          #!/bin/bash
-          mvn clean install -DskipTests -PskipPython,generateDoc
-          if [[ `git status --porcelain` ]]; then
-            echo "Found changes after building, please re-build the CRDs or run ./mvnw spotless:apply and commit the changes. "
-            git status
-            git diff
-            exit 1
-          fi
   # e2e-tests:
   #   name: End to End tests
   #   runs-on: LangStream-4-cores
