s3source: add state and updated/deleted events (#61)
New options on the s3 source:
- `delete-objects` default true, put false to not delete objects once
processed
- `state-storage` (s3, disk) to store the objects and enable
updated/deleted events (complete example
[here](https://github.com/vectorize-io/langstream/pull/61/files#diff-133fd0f51181b2ea3753373f7312443bc86d8d854e5f79c4df1804c615cacec7R76-R78)

in the message header we now set `content_diff` to:
- new -> first time processed
- content_changed -> object already processed but content changed
- no_state_storage -> no state storage configured so we don't know if
it's the first time

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -87,9 +87,29 @@ jobs:
       - name: 'Test: Runtime (Integration Tests)'
         if: ${{ matrix.name == 'Runtime IT' }}
         run: |
+          echo "::group::Build runtime docker images"
           ./mvnw -ntp package -pl ":langstream-runtime-base-docker-image" -Pdocker -DskipTests -PskipPython
+          echo "::endgroup::"
+          echo "::group::Build module"
           ./mvnw -ntp package -pl ":langstream-runtime-impl" -Pdocker -DskipTests -PskipPython
+          echo "::endgroup::"
+          
+          # cleanup intermediate layers to save space
+          docker system prune -f
+          docker image prune -f
+          sudo du -sh *
+          docker images
+          echo "Cleaning up docker images"
+          (docker images | grep -v -e 'langstream' -e 'none' | tail -n +2 | awk -F ' ' '{print $1,":",$2}' | tr -d ' ' | xargs -I {} docker rmi -f {}) || echo "Failed to remove images"
+          echo "After cleanup"
+          docker images
+          sudo du -sh *
+          
+
+
+          echo "::group::Run integration tests"
           ./mvnw -ntp failsafe:integration-test failsafe:verify -pl ":langstream-runtime-impl" -PskipPython
+          echo "::endgroup::"
 
       - name: 'Test: Api Gateway'
         if: ${{ matrix.name == 'Api Gateway' }}
